name: 👯‍♂️ Style Changing Request
description: Suggest a style design
title: "[STYLE]: "
labels: [style 💎]
body:
  - type: textarea
    id: style-idea
    attributes:
      label: What's the suggested design idea?
      description: What are the things that you feed needs to be redesigned or updated?
      placeholder: Background image color does not match the content, it should '...'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to see the demo.
      placeholder: Add the required screenshots to explain problem
    validations:
      required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Additional information
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      multiple: false
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: false
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "Have you read the Code of Conduct?"
      options:
        - label: "I have read the [Code of Conduct](https://github.com/motionime/motionime-web/blob/main/CODE_OF_CONDUCT.md)"
          required: true
  - type: markdown
    attributes:
      value: |
        You can also join [**motionime Discord**](https://discord.com/invite/motionime) for any help or support.